### PR TITLE
Fix the kernelSU code

### PR DESCRIPTION
**Pull request by h88782481**
The kernelSU code should be added to the kernel as a soft link, rather than copying the source code directly into the kernel

### CODE REVIEW

**Comment by DevUknown** [comment]
Hello i am the author of this commit.

The script that generates the symbolic link to the kernelsu folder, the only thing it would do is leave garbage in the code, so why keep the folder with the source code when you directly import it from the repository? the only thing that would happen is that it would generate compilation errors because the SYMBOLIC LINK is being generated in a folder that does not exist I do not understand what is the idea of ​​this "patch"

**Comment by h88782481** [comment]
> Hello i am the author of this commit.
> 
> The script that generates the symbolic link to the kernelsu folder, the only thing it would do is leave garbage in the code, so why keep the folder with the source code when you directly import it from the repository? the only thing that would happen is that it would generate compilation errors because the SYMBOLIC LINK is being generated in a folder that does not exist I do not understand what is the idea of ​​this "patch"

The ksu source code is constantly updated, and there is no official support for copying the ksu source code directly to the kernel, which can cause a number of problems, as described in the ksu official documentation

**Comment by h88782481** [comment]
> Hello i am the author of this commit.
> 
> The script that generates the symbolic link to the kernelsu folder, the only thing it would do is leave garbage in the code, so why keep the folder with the source code when you directly import it from the repository? the only thing that would happen is that it would generate compilation errors because the SYMBOLIC LINK is being generated in a folder that does not exist I do not understand what is the idea of ​​this "patch"

After directly copying the source code and compiling it, the version of the ksu is always fixed to one version, which causes some modules to not work properly

**Comment by h88782481** [comment]
If you still don't understand, take a look at the introduction of ksu integrating KSU for non-Gki kernels
https://kernelsu.org/guide/how-to-integrate-for-non-gki.html

**Comment by h88782481** [comment]
It is also free to specify the version of the ksu via a soft link, rather than being limited to the version copied into the kernel source code

**Comment by DevUknown** [comment]
Ok thanks for the pull request im understand now im fix

**Comment by DevUknown** [comment]
@Rohail33 fixed please close the pull request

**Comment by Rohail33** [comment]
Oke thanks for the convo guys

**Pull request closed without merging**
